/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.atendente;
import br.edu.imepac.clinica.daos.AtendenteDao;
import br.edu.imepac.clinica.entidades.Atendente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro Fernandes
 */
public class AtendenteListForm extends javax.swing.JFrame {
    // 1. Instância do DAO
    private AtendenteDao atendenteDao = new AtendenteDao();

    // 2. Construtor Configurado
    public AtendenteListForm() {
        initComponents();
        
        // --- O SEGREDO PARA NÃO ABRIR TORTA ---
        this.setLocationRelativeTo(null); // Centraliza na tela
        // this.setExtendedState(MAXIMIZED_BOTH); // Se quiser tela cheia, descomente aqui
        
        carregarTabela(); // Carrega os dados
    }

    // 3. Método para buscar no banco e por na tabela
    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblAtendentes.getModel();
        modelo.setNumRows(0); // Limpa

        List<Atendente> lista = atendenteDao.listarTodos();

        for (Atendente a : lista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getUsuario()
                // Não mostramos a senha por segurança
            });
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AtendenteListForm.class.getName());

    /**
     * Creates new form AtendenteListForm
     */
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtendentes = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Listagem de Atendentes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tblAtendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Usuário"
            }
        ));
        jScrollPane1.setViewportView(tblAtendentes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 820, 300));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 100, 30));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, 30));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 100, 30));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
new AtendenteAddForm().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
int linha = tblAtendentes.getSelectedRow();
if (linha == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um atendente para excluir.");
    return;
}

Long id = Long.valueOf(tblAtendentes.getValueAt(linha, 0).toString());

if (JOptionPane.showConfirmDialog(this, "Tem certeza?", "Excluir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
    if (atendenteDao.excluir(id)) {
        JOptionPane.showMessageDialog(this, "Excluído!");
        carregarTabela();
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao excluir.");
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
int linha = tblAtendentes.getSelectedRow();
if (linha == -1) {
    JOptionPane.showMessageDialog(this, "Selecione um atendente para editar.");
    return;
}

Long id = Long.valueOf(tblAtendentes.getValueAt(linha, 0).toString());

// Abre a tela de update (precisaremos criar essa tela depois)
new AtendenteUpdateForm(id).setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AtendenteListForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAtendentes;
    // End of variables declaration//GEN-END:variables
}
