/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.pacientes;
import br.edu.imepac.clinica.daos.PacienteDao;
import br.edu.imepac.clinica.entidades.Paciente;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author Pedro Fernandes
 */
public class GestaoPacientesForm extends javax.swing.JFrame {
    // 1. Variáveis de Controle
    private PacienteDao dao = new PacienteDao();
    private Long idSelecionado = null;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    // 2. Construtor (Onde tudo começa)
    public GestaoPacientesForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Centraliza
        configurarMascaras(); // Aplica a formatação nos campos
        carregarTabela();     // Puxa os dados do banco
    }
    // --- Configura as máscaras (CPF, Data, Telefone) ---
    private void configurarMascaras() {
        try {
            // Data: 31/01/2022
            MaskFormatter maskData = new MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
            maskData.install(txtDataNascimento);

            // CPF: 111.111.111-11
            MaskFormatter maskCpf = new MaskFormatter("###.###.###-##");
            maskCpf.setPlaceholderCharacter('_');
            maskCpf.install(txtCpf);

            // Telefone: (34) 99999-9999
            MaskFormatter maskTel = new MaskFormatter("(##) #####-####");
            maskTel.setPlaceholderCharacter('_');
            maskTel.install(txtTelefone);
            
        } catch (Exception e) {
            System.err.println("Erro ao aplicar máscaras: " + e.getMessage());
        }
    }

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblPacientes.getModel();
        modelo.setNumRows(0);
        
        List<Paciente> lista = dao.listarTodos();
        
        for (Paciente p : lista) {
            // Formata a data para exibir bonito na tabela
            String dataBonita = "";
            if (p.getDataNascimento() != null) {
                dataBonita = p.getDataNascimento().format(formatter);
            }

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                dataBonita, // Exibe dd/MM/yyyy
                p.getTelefone()
            });
        }
    }

   private void limparCampos() {
        // 1. Limpa o campo de texto normal
        txtNome.setText("");
        
        // 2. Limpa os campos formatados (O segredo é usar as duas linhas para cada um)
        txtCpf.setValue(null);
        txtCpf.setText(""); 
        
        txtDataNascimento.setValue(null);
        txtDataNascimento.setText("");
        
        txtTelefone.setValue(null);
        txtTelefone.setText("");
        
        // 3. Reseta o controle da tabela
        idSelecionado = null;
        tblPacientes.clearSelection(); 
        
        // 4. Reativa o botão cadastrar se estiver desligado
        btnCadastrar.setEnabled(true); 
        
        // 5. Põe o cursor no primeiro campo
        txtNome.requestFocus();
    }

    private Paciente montarObjeto() {
        Paciente p = new Paciente();
        p.setNome(txtNome.getText());
        p.setCpf(txtCpf.getText());
        p.setTelefone(txtTelefone.getText());
        
        // Tenta converter o texto da data para LocalDate
        try {
            LocalDate data = LocalDate.parse(txtDataNascimento.getText(), formatter);
            p.setDataNascimento(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Preencha tudo: dia/mês/ano");
            return null; // Retorna nulo se der erro
        }
        return p;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestaoPacientesForm.class.getName());

    /**
     * Creates new form PacienteTela
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        txtSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Gerenciamento de pacientes");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Data de Nascimento:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Contato:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Data Nasc", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        txtSair.setText("Sair");
        txtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDataNascimento))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefone))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNome)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar)))
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSair)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDeletar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
if (idSelecionado == null) {
    JOptionPane.showMessageDialog(this, "Selecione para deletar.");
    return;
}
if (JOptionPane.showConfirmDialog(this, "Tem certeza?", "Excluir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
    if (dao.excluir(idSelecionado)) {
        JOptionPane.showMessageDialog(this, "Excluído!");
        limparCampos();
        carregarTabela();
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
limparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
Paciente p = montarObjeto();
if (p != null) { // Só salva se a data estiver certa
    if (dao.salvar(p)) {
        JOptionPane.showMessageDialog(this, "Sucesso!");
        limparCampos();
        carregarTabela();
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao salvar.");
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
// Verifica se clicou na tabela antes
        if (idSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente na tabela para atualizar.");
            return;
        }

        // Pega os dados alterados dos campos
        Paciente p = montarObjeto();
        
        if (p != null) {
            p.setId(idSelecionado); // IMPORTANTE: Usa o ID capturado no clique!

            if (dao.atualizar(p)) {
                JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
                limparCampos();   // Limpa tudo
                carregarTabela(); // Atualiza a lista
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar.");
            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
// 1. Descobre qual linha foi clicada (0, 1, 2...)
        int linha = tblPacientes.getSelectedRow();

        if (linha != -1) {
            // 2. Pega o ID (que está escondido ou na coluna 0) e guarda na variável global
            // Isso é CRUCIAL para o botão 'Atualizar' saber quem alterar
            Object valorId = tblPacientes.getValueAt(linha, 0);
            this.idSelecionado = Long.valueOf(valorId.toString());

            // 3. Pega os dados das colunas e joga nos campos de texto
            // Nota: As colunas começam em 0. Verifique se a ordem bate com a sua tabela!
            
            // Coluna 1: Nome
            txtNome.setText(tblPacientes.getValueAt(linha, 1).toString());

            // Coluna 2: CPF (O campo formatado aceita o texto direto)
            txtCpf.setText(tblPacientes.getValueAt(linha, 2).toString());

            // Coluna 3: Data de Nascimento
            txtDataNascimento.setText(tblPacientes.getValueAt(linha, 3).toString());

            // Coluna 4: Telefone
            txtTelefone.setText(tblPacientes.getValueAt(linha, 4).toString());

            // 4. Trava o botão "Cadastrar" para evitar criar duplicado sem querer
            btnCadastrar.setEnabled(false);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_tblPacientesMouseClicked

    private void txtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSairActionPerformed
   this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_txtSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestaoPacientesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JButton txtSair;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
