/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens;

import br.edu.imepac.clinica.screens.especialidades.EspecialidadeAddForm;
import br.edu.imepac.clinica.screens.especialidades.EspecialidadeListForm;
import br.edu.imepac.clinica.screens.medicos.MedicoAddForm;
import br.edu.imepac.clinica.screens.medicos.MedicoListForm;
import br.edu.imepac.clinica.screens.medicos.MedicoUpdateForm;

/**
 *
 * @author evertonhf
 */
public class MainMenu extends BaseScreen {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        ajustarLarguraTela();
        posicionarTopo(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        especialidadeMenu = new javax.swing.JMenu();
        cadastrarEspecialidade = new javax.swing.JMenuItem();
        listarEspecialidade = new javax.swing.JMenuItem();
        medicoMenu = new javax.swing.JMenu();
        cadastrarMedico = new javax.swing.JMenuItem();
        listarMedico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mntmPacientes = new javax.swing.JMenuItem();
        mntmListarPacientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mntmListarAtendentes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        especialidadeMenu.setText("Especialidades");

        cadastrarEspecialidade.setText("Cadastrar");
        cadastrarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadeActionPerformed(evt);
            }
        });
        especialidadeMenu.add(cadastrarEspecialidade);

        listarEspecialidade.setText("Listagem");
        listarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEspecialidadeActionPerformed(evt);
            }
        });
        especialidadeMenu.add(listarEspecialidade);

        jMenuBar1.add(especialidadeMenu);

        medicoMenu.setText("Medicos");

        cadastrarMedico.setText("Cadastrar");
        cadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(cadastrarMedico);

        listarMedico.setText("Listagem");
        listarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(listarMedico);

        jMenuBar1.add(medicoMenu);

        jMenu1.setText("Pacientes");

        mntmPacientes.setText("Novo Paciente");
        mntmPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(mntmPacientes);

        mntmListarPacientes.setText("Listar Pacientes");
        mntmListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmListarPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(mntmListarPacientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Atendentes");

        mntmListarAtendentes.setText("Novo Atendente");
        mntmListarAtendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmListarAtendentesActionPerformed(evt);
            }
        });
        jMenu2.add(mntmListarAtendentes);

        jMenuItem2.setText("Listar Atendentes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadeActionPerformed
        EspecialidadeAddForm especialidadeAddForm = new EspecialidadeAddForm();
        especialidadeAddForm.pack();
        especialidadeAddForm.setVisible(true);
    }//GEN-LAST:event_cadastrarEspecialidadeActionPerformed

    private void listarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEspecialidadeActionPerformed
       EspecialidadeListForm especialidadeListForm = new EspecialidadeListForm();
       especialidadeListForm.pack();
       especialidadeListForm.setVisible(true);
    }//GEN-LAST:event_listarEspecialidadeActionPerformed

    private void cadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMedicoActionPerformed
        MedicoAddForm medicoAddForm = new MedicoAddForm();
        medicoAddForm.pack();
        medicoAddForm.setVisible(true);
    }//GEN-LAST:event_cadastrarMedicoActionPerformed

    private void listarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMedicoActionPerformed
        MedicoListForm medicoListForm = new MedicoListForm();
        medicoListForm.pack();
        medicoListForm.setVisible(true);
    }//GEN-LAST:event_listarMedicoActionPerformed

    private void mntmPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmPacientesActionPerformed
new br.edu.imepac.clinica.screens.pacientes.PacienteAddForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mntmPacientesActionPerformed

    private void mntmListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmListarPacientesActionPerformed
new br.edu.imepac.clinica.screens.pacientes.PacienteListForm().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_mntmListarPacientesActionPerformed

    private void mntmListarAtendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmListarAtendentesActionPerformed
// Abre a tela de cadastro
    br.edu.imepac.clinica.screens.atendente.AtendenteAddForm telaCadastro 
            = new br.edu.imepac.clinica.screens.atendente.AtendenteAddForm();
    telaCadastro.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mntmListarAtendentesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// Abre a tela de listagem
    br.edu.imepac.clinica.screens.atendente.AtendenteListForm telaLista 
            = new br.edu.imepac.clinica.screens.atendente.AtendenteListForm();
    telaLista.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarEspecialidade;
    private javax.swing.JMenuItem cadastrarMedico;
    private javax.swing.JMenu especialidadeMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem listarEspecialidade;
    private javax.swing.JMenuItem listarMedico;
    private javax.swing.JMenu medicoMenu;
    private javax.swing.JMenuItem mntmListarAtendentes;
    private javax.swing.JMenuItem mntmListarPacientes;
    private javax.swing.JMenuItem mntmPacientes;
    // End of variables declaration//GEN-END:variables
}
