/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens;
import br.edu.imepac.clinica.screens.atendente.GestaoAtendentesForm;
import br.edu.imepac.clinica.screens.pacientes.GestaoPacientesForm;
import br.edu.imepac.clinica.screens.convenio.GestaoConveniosForm;
import br.edu.imepac.clinica.screens.convenio.RelatorioConvenioForm;
import br.edu.imepac.clinica.screens.consultas.GestaoConsultasForm;
import br.edu.imepac.clinica.screens.medicos.GestaoMedicosForm;
import br.edu.imepac.clinica.screens.RelatorioForm;
import br.edu.imepac.clinica.screens.especialidades.GestaoEspecialidadesForm;
/**
 *
 * @author Pedro Fernandes
 */
public class PainelAtendenteForm extends javax.swing.JFrame {
    private String nomeUsuario;

    // Construtor 1: Recebe o Nome (Usado pelo Login)
    public PainelAtendenteForm(String nome) {
        initComponents();
        this.nomeUsuario = nome;
        this.setLocationRelativeTo(null);
        try {
             lblBoasVindas.setText("Bem-vindo(a), " + nome);
        } catch (Exception e) {}
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelAtendenteForm.class.getName());

    /**
     * Creates new form PainelAtendenteForm
     */
   public PainelAtendenteForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBoasVindas = new javax.swing.JLabel();
        btnAtendentes = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtConvenios = new javax.swing.JButton();
        txtConsultas = new javax.swing.JButton();
        txtRelatorio = new javax.swing.JButton();
        txtEspecialidades = new javax.swing.JButton();
        txtRelConvenio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Painel Administrativo");

        lblBoasVindas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblBoasVindas.setText("Bem-vindo(a) ao sistema.");

        btnAtendentes.setText("Gerenciar Atendentes");
        btnAtendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendentesActionPerformed(evt);
            }
        });

        btnPacientes.setText("Gerenciar Pacientes");
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });

        btnMedicos.setText("Gerenciar Médicos");
        btnMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtConvenios.setText("Gerenciar Convenios");
        txtConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConveniosActionPerformed(evt);
            }
        });

        txtConsultas.setText("Gerenciar Consultas");
        txtConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultasActionPerformed(evt);
            }
        });

        txtRelatorio.setText("Relatorios");
        txtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelatorioActionPerformed(evt);
            }
        });

        txtEspecialidades.setText("Gerenciar Especialidades");
        txtEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadesActionPerformed(evt);
            }
        });

        txtRelConvenio.setText("Paciente Por Convenios");
        txtRelConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelConvenioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblBoasVindas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRelConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConvenios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAtendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEspecialidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBoasVindas)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConvenios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRelConvenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtendentes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendentesActionPerformed
    new GestaoAtendentesForm().setVisible(true);    }//GEN-LAST:event_btnAtendentesActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
    new GestaoPacientesForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
    new GestaoMedicosForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    // Fecha o painel e volta para o Login
    new LoginScreen().setVisible(true);
    this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConveniosActionPerformed
    new GestaoConveniosForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtConveniosActionPerformed

    private void txtConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultasActionPerformed
    new GestaoConsultasForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultasActionPerformed

    private void txtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelatorioActionPerformed
new RelatorioForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelatorioActionPerformed

    private void txtEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadesActionPerformed
new GestaoEspecialidadesForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadesActionPerformed

    private void txtRelConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelConvenioActionPerformed
new RelatorioConvenioForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelConvenioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelAtendenteForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtendentes;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBoasVindas;
    private javax.swing.JButton txtConsultas;
    private javax.swing.JButton txtConvenios;
    private javax.swing.JButton txtEspecialidades;
    private javax.swing.JButton txtRelConvenio;
    private javax.swing.JButton txtRelatorio;
    // End of variables declaration//GEN-END:variables
}
