/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.medicos;

import br.edu.imepac.clinica.daos.ConsultasDao;
import br.edu.imepac.clinica.entidades.Consulta;
import br.edu.imepac.clinica.entidades.Medico;
import br.edu.imepac.clinica.enums.StatusConsulta;
import br.edu.imepac.clinica.screens.LoginScreen;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// Importante: Importar a tela de atendimento
import br.edu.imepac.clinica.screens.medicos.RealizarAtendimentoForm;
/**
 *
 * @author Pedro Fernandes
 */
public class MedicoAgendaForm extends javax.swing.JFrame {
    // 1. Variáveis de Controle
     private ConsultasDao consultaDao = new ConsultasDao();
    private Medico medicoLogado;
    private Long idConsultaSelecionada = null;
    
    // Formatador para a hora (14:30)
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");

    /**
     * Construtor Especial: Recebe o Médico que fez login
     */
    public MedicoAgendaForm(Medico m) {
        initComponents();
        this.medicoLogado = m;
        this.setLocationRelativeTo(null);
        
        // Mostra o nome no topo
        if (m != null) {
            lblNomeMedico.setText("Olá, Dr(a). " + m.getNome());
        }
        
        carregarMinhaAgenda(); // Busca só as consultas dele
    }

    // Construtor Vazio (Necessário para o NetBeans)
    public MedicoAgendaForm() {
        initComponents();
    }

    private void carregarMinhaAgenda() {
        DefaultTableModel modelo = (DefaultTableModel) tblAgenda.getModel();
        modelo.setNumRows(0);
        
        List<Consulta> todas = consultaDao.listarTodos();
        
        // Verifica se a caixinha está marcada
        boolean queroVerHistorico = chkVerRealizadas.isSelected();
        
        for (Consulta c : todas) {
            if (c.getMedico() == null) continue;

            // Filtro 1: É meu?
            boolean ehMeu = c.getMedico().getId() == medicoLogado.getId();
            
            // Filtro 2: Status (Depende do Checkbox)
            boolean statusCorreto;
            if (queroVerHistorico) {
                // Se marcou a caixa, mostra as REALIZADAS
                statusCorreto = c.getStatus() == StatusConsulta.REALIZADA;
            } else {
                // Se não marcou, mostra só as pendentes (AGENDADA)
                statusCorreto = c.getStatus() == StatusConsulta.AGENDADA;
            }
            
            if (ehMeu && statusCorreto) {
                String hora = c.getDataHora() != null ? c.getDataHora().format(formatter) : "";
                modelo.addRow(new Object[]{
                    c.getId(),
                    hora,
                    c.getPaciente().getNome(),
                    c.getObservacoes(),
                    c.getStatus()
                });
            }
        }
        
        // Muda o texto do botão dependendo do modo
        if (queroVerHistorico) {
            btnAtender.setText("Ver Prontuário");
        } else {
            btnAtender.setText("Realizar Atendimento");
        }
    }


    // Construtor Vazio (Necessário para o NetBeans não dar erro)
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicoAgendaForm.class.getName());

    /**
     * Creates new form MedicoAgendaForm
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNomeMedico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        btnAtender = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        chkVerRealizadas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Minha Agenda do Dia");

        lblNomeMedico.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomeMedico.setText("Olá, Dr(a): ");

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Hora", "Paciente", "Observações", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgenda);

        btnAtender.setForeground(new java.awt.Color(51, 255, 51));
        btnAtender.setText("Realizar Atendimento");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar Lista");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        chkVerRealizadas.setText("Ver Realizadas");
        chkVerRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVerRealizadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chkVerRealizadas))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAtender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkVerRealizadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeMedico)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
carregarMinhaAgenda();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        if (idConsultaSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione um paciente na tabela para atender.");
            return;
        }
        
        // Abre a tela de Prontuário passando o ID da consulta
        new RealizarAtendimentoForm(idConsultaSelecionada).setVisible(true);
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void tblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgendaMouseClicked
int linha = tblAgenda.getSelectedRow();
        if (linha != -1) {
            // Pega o ID da consulta (Coluna 0)
            Object valorId = tblAgenda.getValueAt(linha, 0);
            
            // Converte Object para Long de forma segura
            idConsultaSelecionada = Long.valueOf(valorId.toString());
            
            // Destrava o botão verde
            btnAtender.setEnabled(true);
        }
    }//GEN-LAST:event_tblAgendaMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       this.dispose();        // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void chkVerRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVerRealizadasActionPerformed
        carregarMinhaAgenda();
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVerRealizadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MedicoAgendaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox chkVerRealizadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeMedico;
    private javax.swing.JTable tblAgenda;
    // End of variables declaration//GEN-END:variables
}

