/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.medicos;

import br.edu.imepac.clinica.daos.EspecialidadeDao;
import br.edu.imepac.clinica.daos.MedicoDao;
import br.edu.imepac.clinica.entidades.Especialidade;
import br.edu.imepac.clinica.entidades.Medico;
import br.edu.imepac.clinica.exceptions.CampoObrigatorioException;
import br.edu.imepac.clinica.screens.BaseScreen;
import br.edu.imepac.clinica.utils.ConstantesImages;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import br.edu.imepac.clinica.entidades.Perfil;


/**
 *
 * @author evertonhf
 */
public class MedicoAddForm extends BaseScreen {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicoAddForm.class.getName());

    /**
     * Creates new form EspecialidadeAddForm
     */
    public MedicoAddForm() {
        initComponents();
        setImageIcon(ConstantesImages.ESPECIALIDADE_ADD_FORM, imageIcon);
        posicionarTopo(20);
        centralizar();

        loadEspecialidadesInForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        txtCrm = new javax.swing.JLabel();
        crmField = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbEspecialidade = new javax.swing.JComboBox<Especialidade>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Adicionar novo Médico");

        imageIcon.setText("image-icon");

        txtNome.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtNome.setText("Nome");

        txtCrm.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        txtCrm.setText("CRM");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Labels em negrito indicam campos obrigatórios e devem ser preenchidos");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Especialidade");

        cbEspecialidade.setEditable(true);
        cbEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome)
                            .addComponent(txtCrm)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbEspecialidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crmField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnLimpar)
                            .addComponent(btnFechar)))
                    .addComponent(imageIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (!campoObrigatoriosValidos()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Medico medico = new Medico();
            medico.setNome(nomeField.getText());
            medico.setCrm(crmField.getText());
            
            // Pega Especialidade
            Especialidade esp = (Especialidade) cbEspecialidade.getSelectedItem();
            medico.setEspecialidade(esp);
            medico.setEspecialidadeId(esp.getId());

            // Vínculo com Perfil (Obrigatório agora)
            Perfil p = new Perfil();
            p.setId(1); // ID 1 fixo por enquanto
            medico.setPerfil(p);

            if (new MedicoDao().salvar(medico)) {
                JOptionPane.showMessageDialog(this, "Sucesso!");
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        limparFormmulario();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparFormmulario();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cbEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadeActionPerformed

    private void limparFormmulario() {
        nomeField.setText("");
        crmField.setText("");
    }

    private boolean campoObrigatoriosValidos() {
        if (nomeField.getText().isBlank()) {
            return false;
        }
        if (crmField.getText().isBlank()) {
            return false;
        }
        if (especialidadesField.getSelectedItem() == null) {
            return false;
        }
        return true;
    }

    private void loadEspecialidadesInForm() {
        List<Especialidade> especialidades = this.especialidadeDao.listarTodos();

        // Cria o modelo do combo
        DefaultComboBoxModel<Especialidade> modelo = new DefaultComboBoxModel<>();

        // Percorre a lista e adiciona os nomes das especialidades
        for (Especialidade e : especialidades) {
            modelo.addElement(e);
        }

        // Define o modelo no combobox
        especialidadesField.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEspecialidade;
    private javax.swing.JTextField crmField;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel txtCrm;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables

 private final EspecialidadeDao especialidadeDao = new EspecialidadeDao();

    private void limparFormulario() {
        nomeField.setText("");
        crmField.setText("");
        if(cbEspecialidade.getItemCount() > 0) {
            cbEspecialidade.setSelectedIndex(0);
        }
    }

    private boolean campoObrigatoriosValidos() {
        return !nomeField.getText().trim().isEmpty() && 
               !crmField.getText().trim().isEmpty() && 
               cbEspecialidade.getSelectedItem() != null;
    }

    private void loadEspecialidadesInForm() {
        List<Especialidade> especialidades = this.especialidadeDao.listarTodos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Especialidade e : especialidades) {
            modelo.addElement(e);
        }
        cbEspecialidade.setModel(modelo);
    }
}
