/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.medicos;
import br.edu.imepac.clinica.daos.ConsultasDao;
import br.edu.imepac.clinica.daos.ProntuarioDao;
import br.edu.imepac.clinica.entidades.Consulta;
import br.edu.imepac.clinica.entidades.Prontuario;
import br.edu.imepac.clinica.enums.StatusConsulta;
import javax.swing.JOptionPane;
/**
 *
 * @author Pedro Fernandes
 */
public class RealizarAtendimentoForm extends javax.swing.JFrame {
    private ConsultasDao consultaDao = new ConsultasDao();
    private ProntuarioDao prontuarioDao = new ProntuarioDao();
    
    // Variáveis de Controle
    private Long idConsulta;
    private Consulta consultaAtual;

    /**
     * Construtor Especial: Recebe o ID da Consulta selecionada na agenda.
     */
    public RealizarAtendimentoForm(Long idConsulta) {
        initComponents();
        this.idConsulta = idConsulta;
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        carregarDadosConsulta();
    }

    // Construtor vazio para o NetBeans não dar erro
    public RealizarAtendimentoForm() {
        initComponents();
    }

    private void carregarDadosConsulta() {
        // Busca a consulta completa (com nome do paciente)
        this.consultaAtual = consultaDao.buscarPorId(idConsulta);
        
        if (consultaAtual != null) {
            lblNomePaciente.setText("Paciente: " + consultaAtual.getPaciente().getNome());
            
            // Verifica se já existia um prontuário salvo (modo edição)
            Prontuario p = prontuarioDao.buscarPorIdConsulta(idConsulta);
            if (p != null) {
                txtHistorico.setText(p.getHistorico());
                txtReceituario.setText(p.getReceituario());
                txtExames.setText(p.getExames());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao carregar consulta.");
            this.dispose();
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RealizarAtendimentoForm.class.getName());

    /**
     * Creates new form RealizarAtendimentoForm
     */
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceituario = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtExames = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Prontuário Médico");

        lblNomePaciente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNomePaciente.setText("Paciente:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Histórico / Queixas:");

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Receituário:");

        txtReceituario.setColumns(20);
        txtReceituario.setRows(5);
        jScrollPane2.setViewportView(txtReceituario);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Pedido de Exames:");

        txtExames.setColumns(20);
        txtExames.setRows(5);
        jScrollPane3.setViewportView(txtExames);

        btnFinalizar.setText("Finalizar Atendimento");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(lblNomePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(579, 579, 579))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblNomePaciente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(btnFechar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
if (txtHistorico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escreva pelo menos o histórico do paciente.");
            return;
        }

        // 1. Cria ou Atualiza o Prontuário
        // Verifica se já existe para decidir se é INSERT ou UPDATE
        Prontuario prontuarioExistente = prontuarioDao.buscarPorIdConsulta(idConsulta);
        boolean sucesso;

        if (prontuarioExistente == null) {
            // NOVO
            Prontuario novo = new Prontuario();
            novo.setHistorico(txtHistorico.getText());
            novo.setReceituario(txtReceituario.getText());
            novo.setExames(txtExames.getText());
            novo.setConsulta(consultaAtual); // Vincula à consulta
            sucesso = prontuarioDao.salvar(novo);
        } else {
            // ATUALIZAR EXISTENTE
            prontuarioExistente.setHistorico(txtHistorico.getText());
            prontuarioExistente.setReceituario(txtReceituario.getText());
            prontuarioExistente.setExames(txtExames.getText());
            sucesso = prontuarioDao.atualizar(prontuarioExistente);
        }

        if (sucesso) {
            // 2. Muda o status da consulta para REALIZADA
            consultaAtual.setStatus(StatusConsulta.REALIZADA);
            consultaDao.atualizar(consultaAtual);
            
            JOptionPane.showMessageDialog(this, "Atendimento finalizado com sucesso!");
            
            // Fecha esta tela e volta para a agenda (que precisa ser atualizada manualmente ou reaberta)
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar prontuário.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RealizarAtendimentoForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JTextArea txtExames;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextArea txtReceituario;
    // End of variables declaration//GEN-END:variables
}
